# Writing tasks expansion (17 additional variants for Task 1 and Task 2 to reach 25 each)

TASK_1_EXPANSIONS = [
    {
        "id": f"w_task_1_v{v}",
        "variant": v,
        "type": "narrative_personal",
        "title": title,
        "timeSuggestedMinutes": 20,
        "prompt": prompt,
        "wordCount": "120–150 words"
    }
    for v, (title, prompt) in enumerate([
        ("Task 1: Laboratory Equipment Relocation", "You are a senior laboratory technician at a bioscience research institute. Due to ventilation duct maintenance, two specialized centrifuges must be temporarily moved to Basement Room B-12 next Monday. Write an email to all lab personnel explaining the schedule, noting safety precautions for hazardous sample transport, and providing booking instructions for alternative equipment."),
        ("Task 1: Community Arts Center Workshop Feedback", "You organized a weekend woodcarving workshop at a local community center. Write a formal summary letter to the center's program director detailing attendee participation, highlighting constructive feedback regarding workshop ventilation and tool storage, and suggesting two improvements for the autumn program."),
        ("Task 1: University Library Study Pod Reservation Issue", "You are the student representative for postgraduate researchers. Frequent software errors in the library study pod booking system have resulted in double bookings and lost study hours. Write a formal letter to the chief university librarian detailing the recurring technical failures, explaining the impact on thesis completion, and recommending an interim solution."),
        ("Task 1: Public Transportation Route Disruption Advisory", "You are a customer communications officer for a municipal tram network. Urgent track replacement will suspend tram service between Central Station and East Wharf for two weeks. Write a passenger notice explaining the maintenance necessity, detailing replacement bus shuttle frequencies, and outlining season ticket reimbursement procedures."),
        ("Task 1: Ecological Habitat Restoration Volunteer Briefing", "You are the coordinator of a wetlands conservation charity. You have organized a Saturday volunteer planting day along the tidal estuary. Write an orientation email to registered volunteers outlining the rendezvous point, mandatory protective clothing requirements, tool allocation, and safety precautions regarding tidal currents."),
        ("Task 1: Office Renewable Energy Transition Memo", "You are the sustainability officer for an architectural firm. The firm is transitioning its regional headquarters to one hundred percent rooftop solar power this month. Write an internal memorandum to all staff explaining the installation timeline, advising on temporary parking bay closures, and describing new smart lighting controls."),
        ("Task 1: Historic Town Hall Guided Tour Review", "You are a heritage officer who recently audited the weekend guided tour experience at the historic town hall. Write a report to the municipal cultural affairs committee commending the historical accuracy of the guides, identifying accessibility bottlenecks for wheelchair users, and suggesting multilingual audio guide additions."),
        ("Task 1: Medical Clinic Patient Appointment System Update", "You are the practice manager of a busy community medical clinic. The clinic is launching an updated digital patient portal for prescription renewals and routine check-up bookings. Write a clear advisory notice for patients explaining the benefits of the new platform, reassuring elderly patients about telephone booking availability, and providing registration steps."),
        ("Task 1: International Student Orientation Welcome & Guide", "You are the student welfare coordinator at a regional college. A new cohort of sixty international exchange students will arrive next week. Write a welcoming orientation letter explaining airport transfer options, student identity card pickup procedures, and mandatory campus health center registration."),
        ("Task 1: Culinary School Kitchen Appliance Upgrade Request", "You are the head chef instructor at a vocational culinary academy. Several commercial induction ranges in the main training kitchen are malfunctioning, compromising practical exam schedules. Write a formal procurement proposal to the academy dean justifying the immediate replacement with energy-efficient models and providing an estimated budget."),
        ("Task 1: Botanical Garden Rare Orchid Exhibition Notice", "You are the chief horticulturist at a metropolitan botanical garden. A rare tropical orchid is set to bloom for only forty-eight hours in the glasshouse pavilion. Write a public advisory notice explaining the botanical rarity, outlining extended evening visiting hours, and emphasizing photography guidelines with tripod restrictions."),
        ("Task 1: University Sports Complex Renovation Notice", "You are the administrative manager of the campus athletic facilities. The Olympic swimming pool and fitness suite will close for three weeks in August for filtration system overhauls. Write an email to all registered gym members explaining the structural improvements, outlining reciprocal access agreements with neighboring facilities, and detailing automatic membership fee freezes."),
        ("Task 1: Neighborhood Clean Air Zone Consultation Summary", "You are an environmental policy analyst working for an urban borough council. You have completed a public consultation regarding a proposed low-emission vehicle zone. Write an executive summary memorandum to the borough mayor summarizing residents' support for cleaner air, addressing local shopkeepers' concerns regarding delivery access, and proposing delivery loading exemptions."),
        ("Task 1: Freelance Graphic Designer Scope Revision Letter", "You are a freelance creative director commissioned to design a brand identity for a local organic food cooperative. Mid-way through the project, the client requested three additional animated promotional videos not included in the original agreement. Write a professional letter explaining the additional time requirements, outlining a revised milestone schedule, and presenting a transparent supplemental fee structure."),
        ("Task 1: Youth Apprenticeship Program Mentorship Report", "You coordinate a vocational apprenticeship initiative connecting high school graduates with regional manufacturing workshops. Write an interim report to the regional employment board highlighting apprentice retention rates, detailing feedback from master toolmakers, and recommending expanded technical drawing tutorials."),
        ("Task 1: Campus Bicycle Fleet Maintenance Announcement", "You manage the student union shared bicycle initiative. Over the winter break, all eighty fleet bicycles will undergo comprehensive brake and gear refurbishments. Write a notice to student users explaining the scheduled return deadline for bicycles, outlining the penalties for overdue returns, and previewing the newly added electronic locking stations."),
        ("Task 1: Corporate Charity 10K Run Sponsorship Appeal", "You are the corporate social responsibility coordinator for an engineering enterprise. Your office is entering a team into the annual charity run to support a regional youth hospice. Write an engaging email to all department heads encouraging employee participation, explaining corporate donation matching, and providing registration links.")
    ], 9)
]

TASK_2_EXPANSIONS = [
    {
        "id": f"w_task_2_v{v}",
        "variant": v,
        "type": "discursive_analytical",
        "title": title,
        "timeSuggestedMinutes": 25,
        "prompt": prompt,
        "wordCount": "180–220 words"
    }
    for v, (title, prompt) in enumerate([
        ("Task 2: Automation of Public Judicial Decisions", "Some legal theorists argue that utilizing artificial intelligence to assist judicial sentencing could eliminate human racial and socioeconomic bias in the courtroom. Conversely, civil liberties organizations argue that justice fundamentally demands human empathy, situational intuition, and accountability. Write an essay evaluating both arguments and state your own view on algorithmic legal adjudication."),
        ("Task 2: Space Exploration Funding vs. Terrestrial Renewal", "Billions of dollars are allocated annually by governments and private enterprises to deep-space exploration and lunar colonization missions. Critics argue this capital should be redirected exclusively toward urgent terrestrial challenges such as climate mitigation, clean water infrastructure, and poverty relief. Write an essay analyzing both perspectives and give your conclusion."),
        ("Task 2: The Future of Printed Books in the Digital Era", "Despite the ubiquitous convenience of digital e-readers and audiobooks, global sales of physical printed volumes remain remarkably resilient. Some commentators argue that physical books will eventually become obsolete luxury relics, while others maintain that print offers irreplaceable cognitive, tactile, and aesthetic value. Write an essay examining both views."),
        ("Task 2: Compulsory Nutritional Education in Primary Curriculums", "With pediatric obesity and lifestyle-related diabetes increasing globally, public health authorities have proposed making comprehensive nutritional cooking and agricultural education mandatory in all primary schools. Opponents argue that schools are already overburdened with academic core subjects and that dietary habits belong strictly to parental discretion. Write an essay discussing both viewpoints."),
        ("Task 2: Preservation of Historical Architecture in Modern Metropolises", "In rapidly growing cities, older historical structures are frequently demolished to make way for high-capacity modern transit corridors and residential towers. Advocates for development argue modern housing needs must take precedence over sentimentality, while preservationists assert that architectural heritage forms the spiritual and cultural anchor of urban identity. Write an essay on this debate."),
        ("Task 2: Universal Basic Income in the Era of Robotic Automation", "As automation and sophisticated machine learning systems threaten widespread displacement of white-collar and blue-collar professions, economists are debating Universal Basic Income (UBI). Proponents claim UBI guarantees human dignity and spurs creative entrepreneurship, while opponents warn of unsustainable fiscal deficits and diminished work incentives. Write an essay assessing this issue."),
        ("Task 2: Compulsory Second Language Learning in Early Childhood", "Cognitive neuroscientists demonstrate that learning a foreign language before age seven accelerates neuroplasticity and cross-cultural empathy. However, critics claim that early foreign language instruction overburdens young children who are still mastering their native language literacy. Write an essay exploring whether foreign language learning should be mandatory from early childhood."),
        ("Task 2: Regulation of Fast Fashion Production and Environmental Tariffs", "The global fast fashion industry generates millions of tons of textile waste and chemical effluent every year. Some environmental advocates propose introducing strict global carbon tariffs on low-cost synthetic clothing, while manufacturing industry bodies argue such taxes unfairly harm low-income consumers and developing economies reliant on garment exports. Write an essay evaluating this proposal."),
        ("Task 2: High-Stakes Standardized Testing in University Admissions", "Many universities worldwide are moving away from standardized entry examinations, opting instead for holistic portfolios comprising interviews, personal statements, and extracurricular achievements. Proponents celebrate the reduction in student stress, while defenders of standardized tests argue they provide the only objective, meritocratic safeguard against grade inflation and nepotism. Write an essay on this reform."),
        ("Task 2: The Role of Public Subsidies for Independent Journalism", "As commercial advertising revenues shift almost entirely to digital tech monopolies, independent investigative journalism faces unprecedented financial collapse. Some democratic theorists advocate for public government subsidies to preserve investigative newsrooms, whereas skeptics argue state funding inevitably compromises press independence and editorial impartiality. Write an essay analyzing this dilemma."),
        ("Task 2: The Ethical Boundaries of Genetic Modification in Agriculture", "Genetically modified crops engineered for drought tolerance and pest resistance could protect vulnerable populations against climate-induced famines. However, environmental bioethicists warn that modified organisms risk disrupting wild ecosystems and entrenching corporate monopolies over global seed supplies. Write an essay discussing the ethical balance between food security and ecological caution."),
        ("Task 2: Decoupling Economic Growth from Resource Consumption", "Traditional economic models correlate national prosperity with continuous Gross Domestic Product (GDP) growth. However, ecological economists argue that infinite growth on a finite planet is structurally impossible, advocating for steady-state or 'degrowth' paradigms that prioritize human well-being over material expansion. Write an essay examining whether sustained economic growth remains compatible with planetary survival."),
        ("Task 2: The Privatization of Public Healthcare Systems", "Proponents of private healthcare argue that competition and market incentives stimulate clinical innovation, modernize medical technologies, and reduce surgical waiting times. Conversely, champions of state-funded universal healthcare argue that medical care is a fundamental human right that must never be subordinated to corporate profit margins. Write an essay evaluating both perspectives."),
        ("Task 2: Restricting Private Automobile Access in City Centers", "To combat urban carbon emissions and air pollution, several European capitals have banned or heavily taxed private passenger vehicles in central metropolitan districts. Supporters report dramatic decreases in pedestrian accidents and respiratory illnesses, while suburban commuters argue such bans penalize those without access to reliable public rail networks. Write an essay analyzing both sides."),
        ("Task 2: The Social Implications of Cashless Societies", "The transition toward an entirely cashless economy accelerates transaction efficiency and curtails financial crime and black-market tax evasion. However, privacy advocates and social workers warn that cashless systems exclude the unbanked and elderly while granting financial institutions unprecedented surveillance powers over citizen spending. Write an essay discussing whether society should eliminate physical cash."),
        ("Task 2: Intellectual Property Rights and Essential Pharmaceuticals", "During global public health emergencies, pharmaceutical conglomerates argue that strict patent protections are essential to recoup billions invested in clinical trials and stimulate future biomedical research. Global health advocates counter that monopolies on life-saving medicines cost thousands of preventable deaths and that patents must be waived for developing nations. Write an essay on this conflict."),
        ("Task 2: Regulating Micro-Targeted Political Advertising on Social Platforms", "Micro-targeted digital advertising allows political campaigns to tailor messaging to individual psychological profiles, potentially mobilizing disengaged voters. Yet critics argue it fragments public political debate, spreads covert disinformation, and manipulates democratic election outcomes. Write an essay evaluating whether governments should ban micro-targeted political advertising.")
    ], 9)
]
